
apiVersion: v1
kind: Service
metadata:
  name: quiz-backend
  namespace: {{ .Release.Namespace }}
  annotations:
    # Indicate backend uses HTTPS
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    caddy.ingress.kubernetes.io/backend-protocol: "https"
    caddy.ingress.kubernetes.io/upstreams: "https://quiz-backend:443"
    caddy.ingress.kubernetes.io/tls_insecure_skip_verify: "true"
spec:
  selector: { app: quiz-backend }
  ports:
  - port: 443
    targetPort: 8443
    appProtocol: https
    name: https
